/**
 * healthCatalog.mock.js — display CONSTANTS for the Cockpit "Health" view.
 *
 * HealthDashboard is now LIVE (GET /insight-scheduler/health) and no longer reads
 * the per-row pipeline fields below. This file is kept ONLY for the platform /
 * cadence constants it exports — HEALTH_PLATFORMS, PLATFORM_LABEL, CADENCE_LABEL,
 * CADENCE_ORDER, CADENCE_ROLE — which the dashboard's filters + legend use.
 *
 * The INSIGHT_CATALOG array + getHealthTasks() below are the old UI-only stand-in
 * (the spreadsheet's rows with their old Detect→…→Learn stages). They are DEAD —
 * retained only so the constants stay colocated with the catalog they describe.
 * The agents now run the FRAME process (F/R/A/M/E); the live health endpoint
 * supplies each row's `frame` object. Do not wire new code to getHealthTasks().
 */

// The catalog, verbatim from the spreadsheet (one row = one scheduled insight).
export const INSIGHT_CATALOG = [
  {"id":"ins-1","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Spend pace vs. plan","insight":"Budget pacing drift (over/under-spend)","detect":"Actual daily spend crosses +/- threshold vs. planned curve intraday","diagnose":"Capped-by-budget vs. under-delivering (low bid / narrow audience)","recommend":"Re-pace budget to monthly plan; lift bid if under-delivering","simulate":"Projected end-of-month spend & CAC under new pace","act":"Adjust budget within +/-X% guardrail; respect learning-phase lock","learn":"Next-day pace vs. plan; feed error to pacing model"},
  {"id":"ins-2","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"CAC / CPA","insight":"CPA spike vs. baseline","detect":"Changepoint / z-score break on daily CPA vs. trailing baseline","diagnose":"Decompose CPA = CPM x 1/CTR x 1/CVR; isolate driver + entity","recommend":"Throttle driver if auction-led; freeze if data/tracking-led","simulate":"Wasted spend if uncorrected over next 24-72h","act":"Small bid/budget throttle on driver, or raise ticket","learn":"Did CPA revert? Tune anomaly sensitivity"},
  {"id":"ins-3","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"CPL (cost per lead)","insight":"CPL spike on lead-gen campaigns","detect":"Daily CPL breaks above target band vs. trailing 7-day","diagnose":"Lead-volume drop vs. lead-quality/spend rise; find offending campaign","recommend":"Adjust bid/target or pause worst lead source; check form/LP","simulate":"Leads lost & budget wasted if uncorrected","act":"Throttle worst source; flag form/LP if CVR-driven","learn":"CPL recovery; refine lead-quality scoring"},
  {"id":"ins-4","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"CTR %","insight":"CTR drop (ad engagement)","detect":"Daily CTR falls below trailing band on a campaign/creative","diagnose":"Fatigue vs. audience mismatch vs. placement vs. competition","recommend":"Refresh/rotate creative or adjust targeting/placement","simulate":"Projected CPC/CPM relief & downstream CAC impact","act":"Rotate to fresh creative from Asset Lib (Meta); flag for weekly","learn":"CTR recovery per lever; sharpen fatigue triggers"},
  {"id":"ins-5","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"CVR %","insight":"Conversion-rate drop","detect":"Daily CVR down on stable click volume; funnel step drop widens","diagnose":"Localize: audience-quality vs. offer vs. LP vs. price vs. availability","recommend":"Do not over-optimize on 1 day; tighten audience or flag LP/offer","simulate":"CVR uplift -> CAC impact per candidate fix","act":"Ad-side agent tightens targeting; human owns LP/offer","learn":"Which lever moved CVR -> enrich diagnosis playbook"},
  {"id":"ins-6","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"CPM","insight":"CPM spike (auction pressure)","detect":"Daily CPM breaks above baseline on an ad set/campaign","diagnose":"Competition/seasonality vs. audience saturation vs. narrow targeting","recommend":"Broaden audience, cap frequency, or hold bid; avoid over-bidding","simulate":"Efficiency loss vs. reach trade-off at current CPM","act":"Adjust bid/audience within guardrail; flag saturation for weekly","learn":"CPM trend vs. auction benchmarks -> competition model"},
  {"id":"ins-7","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"ROAS","insight":"ROAS drop below target","detect":"Blended/campaign ROAS falls below target vs. trailing 7-day","diagnose":"Revenue-per-conversion vs. CVR vs. spend-mix driver","recommend":"Shift spend to high-ROAS entities; pause worst; check AOV/offer","simulate":"Revenue impact of reallocation vs. status quo","act":"Bounded budget shift; escalate if AOV/pricing-driven","learn":"Realized ROAS vs. predicted -> reallocation model"},
  {"id":"ins-8","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Conversion / pixel events","insight":"Tracking / pixel / conversion break","detect":"Conversions drop to ~0 while spend continues; event-fire gap","diagnose":"Pixel/CAPI/GA event vs. real demand drop (cross-check sessions)","recommend":"Do NOT optimize on corrupt data; freeze auto-actions on scope","simulate":"Mis-optimization risk if bidding continues blind","act":"Alert + freeze downstream agents on scope; escalate to eng","learn":"Log outage window; exclude from baselines to protect models"},
  {"id":"ins-9","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Checkout / payment success rate","insight":"Checkout & payment-gateway errors","detect":"Checkout-start-to-order rate drops; payment-failure/error rate spikes","diagnose":"Gateway failure vs. Apple/Shop Pay silent fail vs. discount-code fail vs. app/script error","recommend":"Roll back recent theme/app/checkout change; fix gateway; halt scaling","simulate":"Orders & revenue lost per hour of broken checkout","act":"Alert + auto-freeze spend scaling; escalate to eng/ops","learn":"Outage window logged; recurring causes -> pre-deploy checks"},
  {"id":"ins-10","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Add-to-cart rate","insight":"Add-to-cart rate drop","detect":"ATC rate falls vs. trailing band on stable sessions","diagnose":"PDP issue (price, image, stock, reviews) vs. traffic-quality shift","recommend":"Fix PDP/price/stock; tighten audience if traffic-quality driven","simulate":"ATC uplift -> downstream orders & CAC","act":"Flag PDP to merch; ad-side agent adjusts targeting","learn":"ATC response per fix -> funnel diagnosis library"},
  {"id":"ins-11","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Cart-to-checkout drop-off","insight":"Cart-to-checkout drop-off spike","detect":"Cart->checkout completion falls vs. baseline, esp. iOS Safari/mobile","diagnose":"Shipping-cost shock vs. mobile UX/keyboard bug vs. limited payment options","recommend":"Fix shipping display/UX; add payment options; segment by device","simulate":"Recovered orders from closing the drop-off","act":"Flag UX to eng; agent holds scaling until fixed","learn":"Device-level drop-off -> CRO backlog priority"},
  {"id":"ins-12","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Site speed / LCP","insight":"Site-speed / page-load regression","detect":"LCP / page-load time regresses past threshold (esp. mobile)","diagnose":"Recent app/script/theme change vs. traffic-mix shift","recommend":"Roll back offending script/app; defer non-critical tags","simulate":"CVR loss attributable to added latency","act":"Flag to eng; pause new heavy scripts","learn":"Speed-vs-CVR elasticity -> perf budget"},
  {"id":"ins-13","platform":"cross","platformLabel":"Cross-Platform","cadence":"daily","cadenceRaw":"Daily","metric":"Zero-conversion spend","insight":"Campaigns spending with zero conversions","detect":"Campaign/ad set spends > X with 0 conversions today","diagnose":"True underperformer vs. low-volume noise via significance gate","recommend":"Throttle/cap spend; queue for pause at weekly review","simulate":"Spend saved with negligible conversion loss","act":"Reduce budget within step-limit; never zero on one day","learn":"Held conversions at lower spend? -> refine gate"},
  {"id":"ins-14","platform":"cross","platformLabel":"Cross-Platform","cadence":"weekly","cadenceRaw":"Weekly","metric":"CAC / ROAS spread","insight":"CAC/ROAS reallocation across campaigns","detect":"7-day CAC/ROAS spread across siblings exceeds efficiency band","diagnose":"Rank by marginal efficiency; check headroom & saturation","recommend":"Move budget low->high marginal in learning-safe steps","simulate":"Blended CAC / total conversions via response curves","act":"Shift budget in bounded, staggered steps","learn":"Realized vs. predicted -> marginal-CAC curves"},
  {"id":"ins-15","platform":"cross","platformLabel":"Cross-Platform","cadence":"weekly","cadenceRaw":"Weekly","metric":"Funnel CVR by step","insight":"Weekly funnel / offer / LP review","detect":"Funnel-step CVRs vs. prior weeks across device/channel/geo","diagnose":"Localize weakest step: audience, offer, LP, price, availability","recommend":"Prioritized offer/LP/audience tests for the week","simulate":"CVR uplift -> CAC impact per test","act":"Queue A/B tests; agent runs ad-side, human owns LP","learn":"Test outcomes -> CRO backlog & playbook"},
  {"id":"ins-16","platform":"cross","platformLabel":"Cross-Platform","cadence":"monthly","cadenceRaw":"Monthly","metric":"Blended CAC by platform","insight":"Budget allocation across platforms","detect":"Marginal CAC/ROAS diverges across Meta/Google/QC/Amazon","diagnose":"Compare marginal efficiency & saturation; account for halo/attribution","recommend":"Rebalance monthly budget toward higher marginal return","simulate":"Blended CAC & revenue via per-platform response curves","act":"Set platform splits on approval; agents pace to them","learn":"Realized CAC vs. plan -> cross-platform model"},
  {"id":"ins-17","platform":"cross","platformLabel":"Cross-Platform","cadence":"monthly","cadenceRaw":"Monthly","metric":"Cohort LTV / repeat rate","insight":"Cohort / LTV & retention shift","detect":"Repeat-rate / 30-60-90d LTV by acquisition cohort moves vs. prior","diagnose":"Tie LTV to acquisition source/creative/segment/product","recommend":"Shift acquisition to high-LTV sources; set LTV-based CAC caps","simulate":"LTV:CAC by channel -> sustainable spend envelope","act":"Update target-CAC guardrails per channel on approval","learn":"Cohort LTV realized -> LTV-aware bidding & targets"},
  {"id":"ins-18","platform":"cross","platformLabel":"Cross-Platform","cadence":"monthly","cadenceRaw":"Monthly / on-demand","metric":"Goal (target ROAS/CAC)","insight":"Goal-driven new campaigns (e.g. 2X ROAS in 14 days)","detect":"Marketer states goal: target ROAS/CAC, horizon, budget","diagnose":"Retrieve historical analogues that hit target for brand/category","recommend":"Assemble plan: audience x product x creative x budget x platform","simulate":"Predicted ROAS/CAC & probability of hitting goal in horizon","act":"Draft full campaign; launch on one-click approval via world-model graph","learn":"Outcome vs. goal -> improve analogue matching & planner"},
  {"id":"ins-19","platform":"cross","platformLabel":"Cross-Platform","cadence":"monthly","cadenceRaw":"Monthly","metric":"LP / CRO backlog","insight":"Landing-page / CRO roadmap","detect":"Aggregate LP CVR by template/offer vs. benchmark","diagnose":"Which pages/steps lose the most conversions & why","recommend":"Prioritized CRO roadmap (speed, layout, trust, checkout)","simulate":"Expected CVR lift & CAC impact per initiative","act":"Approve roadmap; execute over the month","learn":"Realized lift vs. forecast -> CRO scoring"},
  {"id":"ins-20","platform":"meta","platformLabel":"Meta","cadence":"daily","cadenceRaw":"Daily","metric":"Ad review status","insight":"Ad disapprovals / delivery stall","detect":"Entity status = disapproved / not-delivering / policy flag from sync","diagnose":"Map reason code; size spend at risk in the ad set","recommend":"Swap to compliant creative from Asset Lib, or fix targeting/copy","simulate":"Revenue-at-risk from stalled delivery until fixed","act":"Pause offending ad, promote backup creative; notify owner","learn":"Time-to-recovery; recurring codes -> pre-flight policy check"},
  {"id":"ins-21","platform":"meta","platformLabel":"Meta","cadence":"daily","cadenceRaw":"Daily","metric":"Frequency","insight":"Retargeting frequency-cap breach","detect":"Frequency on a retargeting audience crosses fatigue threshold","diagnose":"Over-exposure lifting CPM / cutting CTR on same users","recommend":"Cap frequency, rotate creative, or trim audience window","simulate":"Projected CTR/CPM recovery & CAC impact","act":"Set frequency cap / rotate to fresh creative","learn":"Fatigue-onset curve per audience -> earlier triggers"},
  {"id":"ins-22","platform":"meta","platformLabel":"Meta","cadence":"daily","cadenceRaw":"Daily","metric":"Learning-phase state","insight":"Learning phase limited / reset","detect":"Ad set flips to 'learning limited' or resets after an edit","diagnose":"Budget fragmentation / narrow audience / too-frequent edits","recommend":"Stop editing; consolidate budget to complete learning","simulate":"Expected exit timeline & CAC once stable","act":"Freeze edits during learning; consolidate on approval","learn":"Time-to-exit per structure -> edit-hygiene rules"},
  {"id":"ins-23","platform":"meta","platformLabel":"Meta","cadence":"daily","cadenceRaw":"Daily","metric":"CPM by ad set","insight":"Per-ad-set CPM spike","detect":"Ad-set CPM breaks above its baseline intraday","diagnose":"Auction competition vs. audience saturation vs. narrow targeting","recommend":"Broaden/rotate; hold bid; queue overlap check for weekly","simulate":"Reach & CAC impact at elevated CPM","act":"Adjust within guardrail; flag saturation","learn":"CPM vs. auction benchmarks -> competition signal"},
  {"id":"ins-24","platform":"meta","platformLabel":"Meta","cadence":"daily","cadenceRaw":"Daily","metric":"CTR by creative","insight":"Per-creative CTR decay (early fatigue)","detect":"Creative CTR trends down with rising frequency over 3-5 days","diagnose":"Confirm early fatigue vs. day-of-week noise","recommend":"Pre-stage refresh of winning angle for weekly swap","simulate":"Expected CTR/CAC if refreshed now vs. later","act":"Queue refresh; rotate if severe","learn":"Lead-time to fatigue -> proactive refresh cadence"},
  {"id":"ins-25","platform":"meta","platformLabel":"Meta","cadence":"weekly","cadenceRaw":"Weekly","metric":"Frequency + CTR decay","insight":"Creative fatigue -> refresh","detect":"CTR decay + rising frequency + falling first-impression ratio (7d)","diagnose":"Confirm fatigue vs. audience/offer via creative-attribute edges","recommend":"Refresh winning angle from Asset Lib; retire fatigued ad","simulate":"Expected CTR/CVR lift & CAC drop from analogues","act":"Launch refreshed creative; keep top as control","learn":"New vs. old CAC -> thresholds & winning-angle library"},
  {"id":"ins-26","platform":"meta","platformLabel":"Meta","cadence":"weekly","cadenceRaw":"Weekly","metric":"Audience overlap %","insight":"Audience saturation & overlap","detect":"Reach saturation + rising frequency + high inter-audience overlap %","diagnose":"Ad sets bidding on same users (self-competition) via overlap edges","recommend":"Merge/exclude overlapping ad sets; expand or refresh seed","simulate":"CPM relief & incremental reach from de-overlapping","act":"Apply exclusions / consolidate ad sets on approval","learn":"Post-change CPM & reach -> overlap thresholds"},
  {"id":"ins-27","platform":"meta","platformLabel":"Meta","cadence":"weekly","cadenceRaw":"Weekly","metric":"Learning-limited count","insight":"Learning-phase structure (ABO/CBO)","detect":"Too many low-volume ad sets stuck learning-limited","diagnose":"Budget fragmentation / narrow audiences / over-editing","recommend":"Consolidate or move to CBO; concentrate budget to exit","simulate":"Expected exit timeline & post-learning CAC","act":"Restructure within learning-safe rules on approval","learn":"Time-to-exit per structure -> best-practice library"},
  {"id":"ins-28","platform":"meta","platformLabel":"Meta","cadence":"weekly","cadenceRaw":"Weekly","metric":"Placement performance","insight":"Placement efficiency review","detect":"CAC/CVR by placement (Feed, Reels, Stories, Audience Network) diverges","diagnose":"Which placements over/under-deliver vs. creative fit","recommend":"Rebalance or exclude weak placements; tailor creative aspect ratios","simulate":"CAC impact of placement rebalance","act":"Adjust placement mix on approval","learn":"Placement response -> creative-by-placement rules"},
  {"id":"ins-29","platform":"meta","platformLabel":"Meta","cadence":"weekly","cadenceRaw":"Weekly","metric":"Emerging segment CVR","insight":"New converting segment -> lookalike","detect":"A geo/demo/interest cohort's CVR & volume rising over 2-3 weeks","diagnose":"Confirm durable (not promo/seasonal); find strongest seed","recommend":"Build lookalike / expand targeting; propose a campaign","simulate":"Predicted CAC/ROAS from historical LAL analogues","act":"Draft campaign; launch on approval","learn":"Actual vs. predicted -> seed selection & matching"},
  {"id":"ins-30","platform":"meta","platformLabel":"Meta","cadence":"monthly","cadenceRaw":"Monthly","metric":"Converter profile","insight":"Audience strategy (new LAL, interest, persona)","detect":"Converter profile drifting; best segments plateauing on reach","diagnose":"Where growth remains (new personas/geos) vs. tapped-out seeds","recommend":"Audience roadmap: seeds to build, interests/geos to test","simulate":"Reach & CAC potential per proposed audience","act":"Approve roadmap; execute over the month","learn":"Segment performance vs. forecast -> persona & seed models"},
  {"id":"ins-31","platform":"meta","platformLabel":"Meta","cadence":"monthly","cadenceRaw":"Monthly","metric":"Creative-attribute win-rate","insight":"Creative-concept roadmap (winning angles)","detect":"Aggregate performance by hook/angle/format/offer attributes","diagnose":"Durable winning concept vs. novelty; under-explored angles","recommend":"Next-month test roadmap: double-down / retire / explore","simulate":"Expected win-rate & CAC of the concept slate","act":"Brief production; schedule test calendar","learn":"Concept win-rates -> winning-angle library"},
  {"id":"ins-32","platform":"meta","platformLabel":"Meta","cadence":"monthly","cadenceRaw":"Monthly","metric":"Prospecting:RT ratio","insight":"Funnel structure (prospecting vs. retargeting)","detect":"RT share high with diminishing incrementality; thin top-of-funnel","diagnose":"Estimate incrementality of RT vs. prospecting","recommend":"Rebalance split toward prospecting for durable growth","simulate":"Incremental new customers & blended CAC at new split","act":"Set prospecting:RT ratio on approval; agents pace","learn":"Incrementality realized -> funnel-balance model"},
  {"id":"ins-33","platform":"google","platformLabel":"Google","cadence":"daily","cadenceRaw":"Daily","metric":"Lost IS (budget)","insight":"Budget-capped campaign (limited by budget)","detect":"Campaign flagged budget-limited with healthy ROAS/impression share loss","diagnose":"Confirm efficient demand left on the table vs. inflated bids","recommend":"Raise budget to capture capped demand, within plan","simulate":"Incremental conversions vs. added spend","act":"Lift budget within +/-X% guardrail","learn":"Captured demand vs. predicted -> pacing model"},
  {"id":"ins-34","platform":"google","platformLabel":"Google","cadence":"daily","cadenceRaw":"Daily","metric":"Search terms","insight":"Irrelevant / high-spend search term","detect":"New term with spend + 0 conv + low relevance","diagnose":"Intent mismatch vs. genuinely new converting query","recommend":"Add as negative keyword at ad-group/campaign level","simulate":"Spend redirected to converting terms","act":"Apply negative (reversible); log for weekly review","learn":"Post-negative efficiency delta -> relevance classifier"},
  {"id":"ins-35","platform":"google","platformLabel":"Google","cadence":"daily","cadenceRaw":"Daily","metric":"Keyword CPA","insight":"Runaway high-CPA keyword","detect":"Keyword spend > X with ~0 conversions today","diagnose":"True underperformer vs. noise via volume/significance gate","recommend":"Lower bid or cap; if chronic, queue for pause","simulate":"Spend saved at similar conversions","act":"Reduce bid within step-limit; never zero on one day","learn":"Conversions held at lower spend? -> keyword elasticity"},
  {"id":"ins-36","platform":"google","platformLabel":"Google","cadence":"daily","cadenceRaw":"Daily","metric":"Ad review status","insight":"Ad / asset disapprovals","detect":"RSA/asset or ad disapproved / limited from sync","diagnose":"Map policy reason; size affected ad-group spend","recommend":"Swap compliant asset; fix copy/URL","simulate":"Revenue-at-risk until fixed","act":"Pause offending asset; promote backup","learn":"Recurring reasons -> pre-flight policy check"},
  {"id":"ins-37","platform":"google","platformLabel":"Google","cadence":"daily","cadenceRaw":"Daily","metric":"Impression share / rank","insight":"Impression-share drop (lost to rank)","detect":"Search IS drops with 'lost to rank' rising on key terms","diagnose":"Bid vs. Quality Score vs. competitor entry","recommend":"Raise bid on high-intent terms or flag QS fix","simulate":"Traffic & conversions recoverable vs. added CPC","act":"Bid up within ceiling; queue QS work for weekly","learn":"IS regained per lever -> bid/QS model"},
  {"id":"ins-38","platform":"google","platformLabel":"Google","cadence":"daily","cadenceRaw":"Daily","metric":"PMax spend/return","insight":"PMax spend anomaly","detect":"PMax spend spikes or return collapses vs. baseline","diagnose":"Asset-group/listing-group vs. audience-signal vs. feed issue","recommend":"Adjust budget/target; check feed; add brand exclusions","simulate":"Efficiency impact if uncorrected","act":"Throttle within guardrail; flag feed to weekly","learn":"PMax response -> asset-signal tuning"},
  {"id":"ins-39","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"Search-term report","insight":"Search-term harvesting","detect":"Converting terms accumulating under broad/auto with good ROAS","diagnose":"Sustained conversions + volume; not already exact","recommend":"Promote to exact/phrase or dedicated campaign; set bid","simulate":"Efficiency gain from tighter match & bid control","act":"Create exact keyword/ad-group; add negative in donor","learn":"Harvested ROAS vs. donor -> harvest thresholds"},
  {"id":"ins-40","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"Negative-keyword coverage","insight":"Negative-keyword sweep","detect":"Backlog of irrelevant/low-value terms across campaigns","diagnose":"Cluster wasted-spend themes (info, competitor, off-intent)","recommend":"Add negative lists at campaign/account level","simulate":"Wasted spend eliminated","act":"Apply negative lists on approval","learn":"Waste reduction -> shared negative library"},
  {"id":"ins-41","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"tCPA / tROAS vs. target","insight":"Bid-target tuning (tCPA/tROAS)","detect":"Campaign consistently over/under target 7-14d with stable volume","diagnose":"Target mis-set vs. creative/audience/LP issue; check learning","recommend":"Nudge target in small steps toward efficiency frontier","simulate":"Volume-vs-efficiency trade-off at new target","act":"Adjust target within step-limit; cooldown before next","learn":"Volume/CAC response -> efficiency frontier"},
  {"id":"ins-42","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"Quality Score","insight":"Quality Score improvement","detect":"QS drops on key terms (CTR / ad-relevance / LP experience)","diagnose":"Which QS component is weak per keyword","recommend":"Improve ad relevance/LP; restructure tight ad groups","simulate":"CPC savings & rank gain from higher QS","act":"Update ads/LP; regroup on approval","learn":"QS movement per change -> QS playbook"},
  {"id":"ins-43","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"RSA asset strength","insight":"RSA / ad-copy asset testing","detect":"Low ad-strength or under-tested headlines/descriptions","diagnose":"Which assets drive CTR/CVR vs. dead weight","recommend":"Replace weak assets; test new angles","simulate":"Expected CTR/CVR lift","act":"Rotate assets on approval","learn":"Asset performance -> copy library"},
  {"id":"ins-44","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"PMax asset-group perf","insight":"PMax asset-group refresh","detect":"Asset-group performance & 'low' asset ratings","diagnose":"Which groups/listings drive return; creative gaps","recommend":"Refresh assets; restructure groups; refine signals","simulate":"Return lift from stronger asset groups","act":"Update assets/signals on approval","learn":"Group response -> PMax structure rules"},
  {"id":"ins-45","platform":"google","platformLabel":"Google","cadence":"weekly","cadenceRaw":"Weekly","metric":"Geo / device performance","insight":"Geo & device bid adjustments","detect":"CAC/CVR diverges by geo and device","diagnose":"Where efficiency is best/worst by segment","recommend":"Apply geo/device bid modifiers","simulate":"CAC impact of modifiers","act":"Set modifiers on approval","learn":"Segment response -> bid-modifier model"},
  {"id":"ins-46","platform":"google","platformLabel":"Google","cadence":"monthly","cadenceRaw":"Monthly","metric":"Account structure","insight":"Account structure review","detect":"Campaign/ad-group sprawl; naming/theme inconsistency","diagnose":"Where structure hurts QS, learning, or reporting","recommend":"Restructure by theme; standardize naming","simulate":"Efficiency & manageability gains","act":"Approve restructure; execute over month","learn":"Post-restructure performance -> structure standards"},
  {"id":"ins-47","platform":"google","platformLabel":"Google","cadence":"monthly","cadenceRaw":"Monthly","metric":"Budget by campaign type","insight":"Budget split across Search/PMax/Shopping/Demand Gen","detect":"Marginal returns diverge across campaign types","diagnose":"Compare marginal efficiency & saturation per type","recommend":"Rebalance monthly budget toward higher marginal return","simulate":"Blended CAC & revenue under reallocation","act":"Set splits on approval; agents pace","learn":"Realized CAC vs. plan -> per-type response model"},
  {"id":"ins-48","platform":"google","platformLabel":"Google","cadence":"monthly","cadenceRaw":"Monthly","metric":"Keyword theme coverage","insight":"Keyword-theme expansion strategy","detect":"Coverage gaps vs. category demand & competitor terms","diagnose":"Untapped high-intent themes worth entering","recommend":"Expansion roadmap: new themes/campaigns to launch","simulate":"Incremental volume & CAC of new themes","act":"Approve; Campaign agent builds over month","learn":"New-theme performance -> expansion scoring"},
  {"id":"ins-49","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Availability by dark-store/pincode","insight":"Stock-out / low availability","detect":"Availability flips OOS/<threshold for hero SKU in >=N catchments","diagnose":"Spend still live on OOS SKU -> burning budget + losing rank","recommend":"Pause/curtail ads for OOS pincodes; shift to in-stock SKUs/geos","simulate":"Spend saved + rank protected vs. do-nothing","act":"Throttle ads in OOS catchments; auto-resume on restock","learn":"Rank recovery post-restock; recurring OOS -> supply flag"},
  {"id":"ins-50","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Share of Voice / rank","insight":"Overnight SoV / keyword-rank drop","detect":"SoV / paid+organic rank on hero keywords falls vs. yesterday","diagnose":"Competitor bid/promo vs. our bid cut vs. availability","recommend":"Reclaim: raise keyword bid to target rank within ACOS ceiling","simulate":"Predicted rank/SoV regain & incremental orders","act":"Bid up to target position; cap by ACOS","learn":"Rank per Rs of bid -> bid-to-rank response curve"},
  {"id":"ins-51","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Share of Search","insight":"Share-of-search drop on category terms","detect":"Our listings' share on category search falls vs. baseline","diagnose":"Competitor push vs. relevance/availability vs. bid","recommend":"Lift bids / fix listing relevance on key category terms","simulate":"Impressions & orders recoverable vs. spend","act":"Bid/relevance fix on approval","learn":"Share-of-search response -> visibility model"},
  {"id":"ins-52","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Keyword ACOS","insight":"Runaway high-ACOS keyword","detect":"Keyword spend > X with ~0 conversions today","diagnose":"Underperformer vs. noise via volume gate","recommend":"Lower bid or cap; queue chronic losers for review","simulate":"Spend saved at similar orders","act":"Reduce bid within step-limit","learn":"Orders held at lower spend? -> QC bid model"},
  {"id":"ins-53","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Competitor price/promo","insight":"Competitor price/promo undercut","detect":"Competitor drops price / launches promo on shared keywords","diagnose":"Impact on our CVR, rank, and SoV","recommend":"Match/adjust bid or flag price/promo response to human","simulate":"Order & share loss if unmatched","act":"Bid response by agent; price/promo flagged to human","learn":"Competitive elasticity -> response playbook"},
  {"id":"ins-54","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Budget burn rate","insight":"Budget exhausted before peak hours","detect":"Daily budget depletes before high-conversion windows","diagnose":"Under-budgeted vs. inefficient early spend","recommend":"Redistribute budget to peak windows; raise cap on winners","simulate":"Orders gained by covering peak demand","act":"Adjust budget/schedule within guardrail","learn":"Hourly conversion curve -> dayparting"},
  {"id":"ins-55","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"daily","cadenceRaw":"Daily","metric":"Ratings / reviews","insight":"Rating/review drop hurting CVR","detect":"Hero SKU rating/review score drops below threshold","diagnose":"Negative reviews / quality issue depressing CVR while ads run","recommend":"Reduce spend on affected SKU; flag quality to brand/ops","simulate":"Wasted spend if CVR stays depressed","act":"Throttle spend on approval; escalate quality issue","learn":"Rating-vs-CVR link -> spend-gating rule"},
  {"id":"ins-56","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"weekly","cadenceRaw":"Weekly","metric":"Keyword ROAS","insight":"Keyword ROAS + new-keyword harvest","detect":"7-day keyword ROAS spread; emerging converting keywords unbid","diagnose":"Winners under-bid vs. losers over-bid; check SoV & stock","recommend":"Rebalance bids to winners; add new keywords; trim losers","simulate":"Incremental orders & blended ROAS","act":"Apply bid changes + additions within ACOS ceiling","learn":"Per-keyword ROAS response -> QC bid model"},
  {"id":"ins-57","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"weekly","cadenceRaw":"Weekly","metric":"Promo lift","insight":"Promo / pricing effectiveness","detect":"Promo-period lift vs. baseline (orders, ROAS, new-user share)","diagnose":"Incremental vs. pull-forward / margin-eroding","recommend":"Continue/kill/reshape promo; align spend to promoted SKUs","simulate":"Net margin-adjusted contribution","act":"Adjust ad weighting to promo SKUs; flag promo change","learn":"Promo elasticity by SKU/city -> promo planning"},
  {"id":"ins-58","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"weekly","cadenceRaw":"Weekly","metric":"Listing quality","insight":"Listing / content quality","detect":"Hero SKUs with weak images/titles/desc vs. CVR benchmark","diagnose":"Which listing elements depress CVR","recommend":"Improve images/titles/content before scaling spend","simulate":"CVR uplift -> order & ROAS impact","act":"Flag content updates; agent scales after fix","learn":"Content-vs-CVR link -> listing standards"},
  {"id":"ins-59","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"weekly","cadenceRaw":"Weekly","metric":"SoV trend","insight":"SoV trend & bid rebalance","detect":"SoV on strategic keywords trending down over the week","diagnose":"Where share is slipping and to whom","recommend":"Rebalance bids to defend priority keywords","simulate":"Share regained per Rs of bid","act":"Apply bid changes on approval","learn":"SoV response -> defend/attack rules"},
  {"id":"ins-60","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"monthly","cadenceRaw":"Monthly","metric":"Geo demand vs. presence","insight":"City / dark-store / geo expansion","detect":"High demand + low presence, or strong comparable catchments","diagnose":"Assess availability, demand density, competitor SoV","recommend":"Prioritized expansion list with stock prerequisites","simulate":"Order & revenue potential per candidate geo","act":"Launch ads in approved catchments once stock confirmed","learn":"New-geo ramp vs. forecast -> expansion scoring"},
  {"id":"ins-61","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"monthly","cadenceRaw":"Monthly","metric":"SKU efficiency","insight":"Hero-SKU selection & under-funded winner","detect":"SKU with strong CVR/margin/repeat but low share of spend","diagnose":"Confirm scalable (stock, SoV headroom, margin) vs. spike","recommend":"Promote to hero: raise budget/priority","simulate":"Incremental revenue & blended CAC from scaling","act":"Reprioritize spend on approval; brief Campaign agent","learn":"Did winner scale efficiently? -> hero scoring"},
  {"id":"ins-62","platform":"quick_commerce","platformLabel":"Blinkit & Zepto","cadence":"monthly","cadenceRaw":"Monthly","metric":"Category SoV","insight":"Category share & competitive positioning","detect":"Category SoV / share-of-search trend vs. named competitors","diagnose":"Where share is won/lost by keyword, SKU, geo","recommend":"Defend/attack plan: where to invest SoV, where to concede","simulate":"Share-point gain per Rs by battleground","act":"Set SoV targets by battleground on approval","learn":"Share moved per Rs -> competitive response model"},
  {"id":"ins-63","platform":"flipkart","platformLabel":"Flipkart","cadence":"daily","cadenceRaw":"Daily","metric":"Buy Box status","insight":"Buy Box loss","detect":"BuyBox lost on an advertised listing","diagnose":"Ads spend but can't convert; cause (price/stock/seller)","recommend":"Pause ads on listing until Buy Box returns; reallocate","simulate":"Wasted ad spend avoided while Buy Box lost","act":"Pause ads on listing; auto-resume on regain; flag pricing","learn":"Buy-Box-loss frequency -> repricer recommendation"},
  {"id":"ins-64","platform":"flipkart","platformLabel":"Flipkart","cadence":"daily","cadenceRaw":"Daily","metric":"SoV / rank","insight":"Overnight SoV / rank drop","detect":"SoV / rank on category keywords falls vs. yesterday","diagnose":"Competitor bid/promo vs. our bid cut vs. availability","recommend":"Raise keyword bid to target rank within ACOS ceiling","simulate":"Rank regain & incremental orders","act":"Bid up to target position; cap by ACOS","learn":"Rank per Rs -> bid-to-rank curve"},
  {"id":"ins-65","platform":"flipkart","platformLabel":"Flipkart","cadence":"daily","cadenceRaw":"Daily","metric":"Keyword ACOS","insight":"Runaway high-ACOS keyword","detect":"High-spend PLA keyword with ~0 conversions","diagnose":"Underperformer vs. noise via volume gate","recommend":"Lower bid or cap; queue chronic losers","simulate":"Spend saved at similar orders","act":"Reduce bid within step-limit","learn":"Response -> bid model"},
  {"id":"ins-66","platform":"flipkart","platformLabel":"Flipkart","cadence":"daily","cadenceRaw":"Daily","metric":"Search terms","insight":"Irrelevant search term","detect":"New search term with spend + 0 conv + low relevance","diagnose":"Intent mismatch vs. new converting query","recommend":"Add as negative keyword","simulate":"Spend redirected to converting terms","act":"Apply negative; log for review","learn":"Efficiency delta -> relevance classifier"},
  {"id":"ins-67","platform":"flipkart","platformLabel":"Flipkart","cadence":"daily","cadenceRaw":"Daily","metric":"Budget pace","insight":"Budget pacing / peak-hour depletion","detect":"Budget depletes before peak or under-delivers","diagnose":"Under-budgeted vs. inefficient early spend","recommend":"Redistribute to peak; raise cap on winners","simulate":"Orders gained by covering peak","act":"Adjust budget within guardrail","learn":"Hourly curve -> dayparting"},
  {"id":"ins-68","platform":"flipkart","platformLabel":"Flipkart","cadence":"weekly","cadenceRaw":"Weekly","metric":"Search-term report","insight":"Search-term harvesting","detect":"Converting terms under broad with good ROAS","diagnose":"Sustained conversions + volume; not already targeted","recommend":"Promote to targeted keyword; add negative in donor","simulate":"Efficiency gain from tighter match","act":"Create keyword; add negative in donor","learn":"Harvested ROAS vs. donor -> thresholds"},
  {"id":"ins-69","platform":"flipkart","platformLabel":"Flipkart","cadence":"weekly","cadenceRaw":"Weekly","metric":"Keyword ROAS / promo","insight":"Keyword ROAS + promo effectiveness","detect":"Keyword ROAS spread; promo lift vs. baseline","diagnose":"Winners under-bid; promo incremental vs. pull-forward","recommend":"Rebalance bids; align spend to promo SKUs","simulate":"Incremental orders & margin-adjusted contribution","act":"Apply bid changes; adjust promo weighting","learn":"Elasticity by keyword/SKU -> models"},
  {"id":"ins-70","platform":"flipkart","platformLabel":"Flipkart","cadence":"weekly","cadenceRaw":"Weekly","metric":"Catalog quality","insight":"Catalog / content quality","detect":"Listings with weak content vs. CVR benchmark","diagnose":"Which elements depress CVR","recommend":"Improve catalog content before scaling","simulate":"CVR uplift -> order impact","act":"Flag content; scale after fix","learn":"Content-vs-CVR -> catalog standards"},
  {"id":"ins-71","platform":"flipkart","platformLabel":"Flipkart","cadence":"monthly","cadenceRaw":"Monthly","metric":"SKU efficiency","insight":"Hero-SKU / ASIN selection","detect":"Listing with strong CVR/margin but low share of spend","diagnose":"Confirm scalable vs. one-off","recommend":"Promote to hero: raise budget/priority","simulate":"Incremental revenue & blended CAC","act":"Reprioritize spend on approval","learn":"Scaled efficiently? -> hero scoring"},
  {"id":"ins-72","platform":"flipkart","platformLabel":"Flipkart","cadence":"monthly","cadenceRaw":"Monthly","metric":"Category SoV","insight":"Category share & positioning","detect":"Category SoV trend vs. competitors","diagnose":"Where share won/lost by keyword/SKU/geo","recommend":"Defend/attack SoV plan","simulate":"Share-point gain per Rs","act":"Set SoV targets on approval","learn":"Share per Rs -> competitive model"},
  {"id":"ins-73","platform":"amazon","platformLabel":"Amazon","cadence":"daily","cadenceRaw":"Daily","metric":"Buy Box status","insight":"Buy Box loss","detect":"BuyBox lost on an advertised ASIN","diagnose":"Ads spend but can't convert without Buy Box; find cause","recommend":"Pause SP/SB on ASIN until Buy Box returns; reallocate","simulate":"Wasted spend avoided while Buy Box lost","act":"Pause ads on ASIN; auto-resume on regain; flag pricing","learn":"Buy-Box-loss frequency -> repricer recommendation"},
  {"id":"ins-74","platform":"amazon","platformLabel":"Amazon","cadence":"daily","cadenceRaw":"Daily","metric":"Keyword ACOS","insight":"Runaway high-ACOS keyword","detect":"Keyword spend > X with ~0 conversions today","diagnose":"Underperformer vs. noise via volume gate","recommend":"Lower bid or cap; queue chronic losers for pause","simulate":"Spend saved at similar conversions","act":"Reduce bid within step-limit","learn":"Response -> keyword elasticity"},
  {"id":"ins-75","platform":"amazon","platformLabel":"Amazon","cadence":"daily","cadenceRaw":"Daily","metric":"Search terms (5+ clicks, 0 sales)","insight":"Irrelevant search term burning spend","detect":"Search term with 5+ clicks and 0 sales today/recent","diagnose":"Intent mismatch vs. new converting query","recommend":"Add as Negative Exact/Phrase","simulate":"Spend redirected to converting terms","act":"Apply negative; log for weekly review","learn":"Efficiency delta -> relevance classifier"},
  {"id":"ins-76","platform":"amazon","platformLabel":"Amazon","cadence":"daily","cadenceRaw":"Daily","metric":"Organic + paid rank","insight":"Overnight SoV / rank drop","detect":"Rank on hero keywords falls vs. yesterday","diagnose":"Competitor bid/promo vs. our bid vs. availability","recommend":"Raise bid to target rank within ACOS ceiling","simulate":"Rank regain & incremental orders","act":"Bid up to target position","learn":"Rank per Rs -> bid-to-rank curve"},
  {"id":"ins-77","platform":"amazon","platformLabel":"Amazon","cadence":"daily","cadenceRaw":"Daily","metric":"Budget burn / hour","insight":"Budget exhausted before peak hours","detect":"Campaign exhausts budget before peak shopping windows","diagnose":"Under-budgeted winners vs. inefficient early spend","recommend":"Raise budget on winners; adjust dayparting","simulate":"Orders gained by covering peak","act":"Adjust budget/schedule within guardrail","learn":"Hourly conversion curve -> dayparting"},
  {"id":"ins-78","platform":"amazon","platformLabel":"Amazon","cadence":"weekly","cadenceRaw":"Weekly","metric":"Search-term report","insight":"Search-term harvesting (Auto -> Exact)","detect":"Auto/broad terms with 2+ conversions and good ACOS","diagnose":"Sustained conversions + volume; not already exact","recommend":"Promote to Exact / dedicated SP campaign; set bid","simulate":"Efficiency gain from tighter control","act":"Create exact keyword; add negative in donor","learn":"Harvested ACOS vs. donor -> thresholds"},
  {"id":"ins-79","platform":"amazon","platformLabel":"Amazon","cadence":"weekly","cadenceRaw":"Weekly","metric":"ACOS / CVR by keyword","insight":"Bid adjustments (rules-based)","detect":"High-ACOS low-CVR keywords; low-impression high-CVR keywords","diagnose":"Overbid losers vs. underbid winners","recommend":"Cut losers bids 15-25%; raise winners 10-20%; tune placement modifiers","simulate":"ACOS/volume impact of the bid moves","act":"Apply bid changes within step-limit; cooldown","learn":"Response -> efficiency frontier"},
  {"id":"ins-80","platform":"amazon","platformLabel":"Amazon","cadence":"weekly","cadenceRaw":"Weekly","metric":"Placement performance","insight":"Placement bid modifiers","detect":"Top-of-search vs. rest-of-search vs. product-page performance diverges","diagnose":"Which placements convert efficiently","recommend":"Adjust placement bid modifiers","simulate":"ACOS impact of modifiers","act":"Set modifiers on approval","learn":"Placement response -> modifier model"},
  {"id":"ins-81","platform":"amazon","platformLabel":"Amazon","cadence":"weekly","cadenceRaw":"Weekly","metric":"SB / SD performance","insight":"Sponsored Brands & Display review","detect":"SB top-keyword performance; SD retargeting/conquesting efficiency","diagnose":"Where SB/SD add incremental vs. cannibalize SP","recommend":"Reallocate to efficient SB/SD; refine audiences","simulate":"Incremental orders vs. SP overlap","act":"Adjust SB/SD budgets on approval","learn":"Incrementality -> full-funnel mix"},
  {"id":"ins-82","platform":"amazon","platformLabel":"Amazon","cadence":"weekly","cadenceRaw":"Weekly","metric":"Inventory weeks-of-cover","insight":"Inventory < 2-week supply","detect":"Advertised ASIN stock drops below ~2-week supply","diagnose":"Risk of stock-out mid-flight wasting rank","recommend":"Reduce bids / pace spend to stretch inventory","simulate":"Rank protected & spend preserved","act":"Throttle bids on approval; alert ops","learn":"Stock-out incidence -> supply-aware pacing"},
  {"id":"ins-83","platform":"amazon","platformLabel":"Amazon","cadence":"weekly","cadenceRaw":"Weekly","metric":"Campaign structure","insight":"Structure & match-type hygiene","detect":"Match types mixed; naming inconsistent; ASIN grouping loose","diagnose":"Where structure blurs signal & harvesting","recommend":"Separate Auto/Broad/Phrase/Exact; regroup by relevance","simulate":"Cleaner data -> better bidding & harvesting","act":"Restructure on approval","learn":"Post-restructure efficiency -> structure standards"},
  {"id":"ins-84","platform":"amazon","platformLabel":"Amazon","cadence":"monthly","cadenceRaw":"Monthly","metric":"TACOS / hero ASIN","insight":"Hero-ASIN selection & budget across SP/SB/SD","detect":"Strong ASIN under-funded; marginal returns diverge by ad type","diagnose":"Scalable winner; efficiency per campaign type","recommend":"Promote hero; rebalance SP/SB/SD budget","simulate":"Incremental revenue & blended TACOS","act":"Reprioritize on approval","learn":"Scaled efficiently? -> hero & type models"},
  {"id":"ins-85","platform":"amazon","platformLabel":"Amazon","cadence":"monthly","cadenceRaw":"Monthly","metric":"Category SoV / DSP","insight":"Category share & upper-funnel","detect":"Category SoV / share-of-search vs. competitors","diagnose":"Where share won/lost by keyword/ASIN; upper-funnel gaps","recommend":"Defend/attack plan; DSP/upper-funnel where needed","simulate":"Share-point gain per Rs","act":"Set SoV targets on approval","learn":"Share per Rs -> competitive model"}]

// Platform FILTER tabs in display order (value must match INSIGHT_CATALOG[].platform).
// "All platforms" (no filter) already surfaces cross-platform/universal agents, so a
// separate "Cross-platform" tab reads as a duplicate to users — dropped here. Cross
// agents still render with their own badge/label (see PLATFORM_LABEL below).
export const HEALTH_PLATFORMS = [
  { value: 'all', label: 'All platforms' },
  { value: 'meta', label: 'Meta' },
  { value: 'google', label: 'Google' },
  { value: 'quick_commerce', label: 'Blinkit & Zepto' },
  { value: 'flipkart', label: 'Flipkart' },
  { value: 'amazon', label: 'Amazon' },
]
// Labels for the platform BADGE on each row — includes 'cross' even though it's no
// longer a filter tab, so a cross-platform agent's badge still renders correctly.
export const PLATFORM_LABEL = HEALTH_PLATFORMS.reduce(
  (a, p) => { a[p.value] = p.label; return a },
  { cross: 'Cross-platform' },
)

export const CADENCE_LABEL = { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', other: 'Custom' }
// Sort order for the run-history / health task list — most→least frequent. Covers
// every cadence key the backend `cadenceOf` can emit so none sort as NaN.
export const CADENCE_ORDER = {
  every_5m: -1, hourly: 0, hourly_working: 1, hourly_day: 2, daily: 3, weekdays: 4, weekly: 5, monthly: 6, once: 7, other: 8,
}
// The catalog's own read of what each cadence is FOR (from the Overview sheet).
export const CADENCE_ROLE = {
  daily: 'Triage & protect — fast signal, mostly reversible, agent-automatable',
  weekly: 'Optimize — enough data for significance; recommend then approve',
  monthly: 'Strategize — structural, slow-signal; engine frames, human decides',
  other: 'Custom cadence',
}

// A fixed reference "now" so synthesized run times read consistently in the mock.
const NOW = new Date('2026-08-07T09:30:00+05:30').getTime()
const HOUR = 3600e3
const DAY = 24 * HOUR

// Deterministic 0..1 hash from a string (no Math.random — stable per id).
function seed(str) {
  let h = 2166136261
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619) }
  return ((h >>> 0) % 100000) / 100000
}

const CADENCE_STEP = { daily: DAY, weekly: 7 * DAY, monthly: 30 * DAY, other: 6 * HOUR }
const CADENCE_BARS = { daily: 7, weekly: 6, monthly: 4, other: 8 }

// Curated ids forced into non-OK states so the fleet always shows a realistic
// mix of critical / needs-review / paused rather than an all-green wall.
const FORCED = {
  'ins-7': 'critical',   // Cross: tracking / pixel break
  'ins-8': 'warn',       // Cross: checkout & payment errors
  'ins-20': 'critical',  // Meta: ad disapprovals / delivery stall
  'ins-24': 'warn',      // Meta: per-creative CTR decay
  'ins-38': 'critical',  // Google: PMax spend anomaly
  'ins-49': 'critical',  // Quick-commerce: stock-out / low availability
  'ins-51': 'warn',      // Quick-commerce: share-of-search drop
  'ins-73': 'warn',      // Amazon: Buy Box loss
  'ins-18': 'paused',
  'ins-45': 'paused',
  'ins-63': 'paused',
}

// A short, plausible run "output" line keyed off the insight.
function runOutputFor(item, runStatus) {
  if (runStatus === 'error') return item.metric + ': guardrail check failed — ' + item.detect.slice(0, 60) + '…'
  if (runStatus === 'running') return 'Evaluating ' + item.metric.toLowerCase() + ' across entities…'
  const clean = seed(item.id + 'clean') > 0.45
  return clean
    ? 'No breach — ' + item.metric.toLowerCase() + ' within band, no action taken'
    : item.insight + ': 1 entity flagged, action staged for approval'
}

// Synthesize one task's runtime health from its catalog row.
function synthesize(item) {
  const s = seed(item.id)
  const step = CADENCE_STEP[item.cadence] || DAY
  const bars = CADENCE_BARS[item.cadence] || 7
  const forced = FORCED[item.id]

  const health = forced || (s > 0.9 ? 'warn' : 'ok')
  const paused = health === 'paused'

  // History (oldest → newest): mostly successes with the odd past blip, then
  // bend the tail to match the target health.
  const hist = []
  for (let i = 0; i < bars; i++) hist.push(seed(item.id + 'h' + i) > 0.92 ? 'error' : 'success')
  if (!paused) {
    if (health === 'critical') hist[bars - 1] = 'error'
    else if (health === 'warn') { hist[bars - 1] = 'success'; hist[bars - 2] = 'error' }
    else hist[bars - 1] = 'success'
  }

  const jitter = Math.floor(s * (step * 0.15))
  const lastRunAt = paused
    ? NOW - step * (2 + Math.floor(s * 3))
    : NOW - jitter - HOUR * (1 + Math.floor(s * 5))
  const nextRunAt = paused ? null : lastRunAt + step

  // Per-run records, newest first, from the history tail.
  const recent = hist.slice().reverse()
  const runs = []
  for (let i = 0; i < Math.min(3, recent.length); i++) {
    const rstatus = recent[i]
    const startedAt = lastRunAt - i * step
    const durS = 20 + Math.floor(seed(item.id + 'd' + i) * 340)
    runs.push({
      id: item.id + '-run-' + i,
      status: rstatus,
      started_at: new Date(startedAt).toISOString(),
      completed_at: new Date(startedAt + durS * 1000).toISOString(),
      duration_s: durS,
      output: runOutputFor(item, rstatus),
      error_message: rstatus === 'error' ? 'Guardrail/precondition failed while evaluating "' + item.metric + '"' : null,
    })
  }

  return {
    ...item,
    status: paused ? 'paused' : 'active',
    health,
    history: paused ? hist.map(() => 'paused') : hist,
    last_run_at: new Date(lastRunAt).toISOString(),
    next_run_at: nextRunAt ? new Date(nextRunAt).toISOString() : null,
    run_count: 12 + Math.floor(s * 180),
    last_error: health === 'critical' ? runs[0] && runs[0].error_message : null,
    runs,
  }
}

// Mock equivalent of "GET /scheduled-jobs (+ per-job runs)". Returns the full
// enriched fleet. Swap this for the live fetch when the backend is ready.
export function getHealthTasks() {
  return INSIGHT_CATALOG.map(synthesize)
}
